[[publishing-considerations]]
== Specific freshwater data publishing considerations

=== Data preparation and standards

GBIF makes use of the Darwin Core Standard (DwC) to provide a standardized framework for formatting data for publication (see What is Darwin Core, and why does it matter?). DwC is a global standard that allows for integration of data from different sources through a common format and a number of required and recommended fields. 

Though GBIF suggests the required and recommended fields for the above-mentioned types of datasets, freshwater datasets need a few more specifications to form useful and re-usable data for global analyses (see section 2). In the following section we provide guidance on all mandatory and recommended terms of the different GBIF data classes and how they are best used when preparing freshwater datasets by giving freshwater-specific examples and recommendations. For some terms we suggest using selected terms only to improve consistency among datasets. To make freshwater data publication as easy as possible we also provide Excel templates for all data classes.

What is important for checklist and occurrence datasets is the inclusion of well-structured scientific names for taxa. When data are uploaded, the taxonomic backbone of GBIF will be used to check taxon names and update nomenclature as needed for consistency with current naming conventions. However, this process relies on a lack of ambiguity in the provided nomenclature. For example, taxonomic names at the genus or species level that are provided without any higher classifications (e.g. kingdom, class) may end up being misclassified by the taxonomic backbone if the same or similar species names are found in different kingdoms. This would result in inaccurate data. GBIF therefore recommends that users provide as much information as possible about higher classifications. Identification qualifiers (e.g. cf.), working names, and common names should not be included in the scientificName field, as these will not align with the taxonomic backbone. Author names are also an important component of scientific names to avoid misclassification, particularly for species-rich groups such as diatoms. The taxonomic authority (author who first published the species name following international rules) as well as the year of naming should be provided where possible, following the rules of author citation (https://code.iczn.org/authorship/article-51-citation-of-names-of-authors/?frame=1[learn about proper citation rules^]).

==== Checklist datasets

Checklist data are not specific to a location and do not represent individual observations. As a result, the fields required for checklist data are minimal compared to other data classes (<<table-04,Table 4>>). The primary focus for these datasets is on the scientific name of the taxon. As noted, higher classifications (i.e., kingdom) are helpful to include in the data to ensure taxa are not misassigned to the wrong name in the taxonomic backbone.

[[table-04]]
.Terms, definitions, examples, and comments for the terms required by GBIF to publish checklist datasets (see https://www.gbif.org/data-quality-requirements-checklists[more information^] on the specific fields).
[cols="%autowidth"]
|===
|term |definition |example(s) |status |comment

|term:dwc[taxonID]
|A unique identifier for the taxon; may be a global unique identifier or an identifier specific to the dataset.
|"8fa58e08-08de-4ac1-b69c-1235340b7001" +
"32567" +
"ID-fwe-32567"
|required
|Ideally, the taxonID is a persistent global unique identifier. As a minimum requirement, it has to be unique within the published dataset.

|term:dwc[scientificName]
|The full scientific name of the organism, to the most precise taxonomic rank that is possible to supply, and including authorship and year of the name where applicable/known	
|"Adicella cremisa Malicky, 1972" [genus + specificEpithet + scientificNameAuthorship]
|required	
|Names should be compliant to the most recent nomenclatural code. This term should not contain identification qualifications (e.g., cf.), which should instead be supplied in the identificationQualifier term. Ideally, the name supplied is at species level or below. Not permitted are, i.e., working names ("Adicella sp.4"), common names ("creamy caddisfly"), or names containing identification qualifiers ("Adicella cf. cremisa").

|term:dwc[taxonRank]
|Taxonomic rank of the most most precise taxonomic level provided in term:dwc[scientificName]
|"kingdom" +
"phylum" +
"class" +
"order" +
"family" +
"subfamily" +
"genus" +
"species" +
"subspecies" +
"varietas" +
"forma"
|required
|Recommended best practice is to use a controlled vocabulary.

|term:dwc[kingdom]
| Full scientific name of the kingdom in which the taxon is classified.
|"Animalia" +
"Plantae" +
"Fungi" +
"Protista" +
"Monera"
|strongly recommended
|Inclusion of kingdom helps to ensure taxa are not misassigned to the wrong taxonomic name in GBIF.

|term:dwc[parentNameUsageID]
|The taxonID of the next available higher-ranked (parent) entry within the checklist dataset, if higher taxon names are supplied as separate entries in the list
|"2704173" (GBIF) +
"tsn:41074" (ITIS)
|strongly recommended
|This supports the representation of the dataset as a hierarchy, e.g. for the publication of a taxonomy. For Darwin Core Archives, the related record should be present locally in the same archive. 

|term:dwc[acceptedNameUsageID]
|Within the record of a synonym, the taxonID of the accepted taxon name entry within the checklist dataset, if both synonyms and accepted names are supplied.
|"2704179" (GBIF) +
"tsn:41107" (ITIS)
|strongly recommended
|This supports the representation of synonymy for a taxonomic dataset. For Darwin Core Archives the related record should be present locally in the same archive.

|===

NOTE: `pink fields indicate that you should choose either of these entries`

==== Occurrence datasets

Occurrence data provide information about observations of taxa and the locations where they were found (<<table-05,Table 5>>). Although only coarse location information is required, the recommended best practice is to always provide coordinates (latitude and longitude in decimal degrees), a geodetic datum, and a measure of the uncertainty around the coordinates (estimated precision). 

Occurrence data can be provided as presence data (i.e., a “1” for a site where the taxon was observed) or as counts in the field individualCount (<<table-05,Table 5>>). Counts in this case refer to situations where there is not an effort to estimate the total abundance of the taxon (i.e. by collecting a sample), but instead, numbers of individuals are recorded (tallied) as individuals are encountered. This could include point counts (i.e., in bird surveys, when an observer counts the number of individuals of each species that is viewed or heard) or opportunistic observations. When an effort is made to estimate, for example, abundance, density, or biomass as part of targeted or assemblage sampling, these measures should be recorded in the field organismQuantity with units recorded in organismQuantityType (Table 5). Ideally, such occurrence data should also be accompanied by sampling-event data to provide details on sampling methods. Finally, if effort has been put into recording true absences (i.e. through systematic and/or extensive sampling procedures), then presence or absence can be recorded in the field occurrenceStatus (<<table-05,Table 5>>). These distinctions will facilitate meta-analysis of data collected in a similar manner or will allow for data to be adjusted as needed for analysis (e.g. all data converted to presence data). 

[[table-05]]
.Terms, definitions, examples, and comments for the terms required by GBIF to publish occurrence datasets (https://www.gbif.org/data-quality-requirements-occurrences[more information^] on specific fields)
[cols="%autowidth"]
|===
|Term	|Freshwater definition |Example |Status |Comment

|term:dwc[occurrenceID]
|Identifier for the Occurrence; in the absence of a persistent global unique identifier, construct one from a combination of identifiers in the record that will most closely make the occurrenceID globally unique
|"AT:BOKU:DAN_0003:8755" [country:institutionCode:sampleCode:speciesID]
|required
|This should be a unique identifier for the occurrence, allowing the same occurrence to be recognised across dataset versions as well as through data downloads and use. At the very least the identifier should be unique to the dataset, and ideally a globally unique identifier.

|===

NOTE: `pink fields indicate that you should choose either of these entries`

==== Sampling-event datasets

When occurrence data have additional metadata describing sampling methods, this is called an event and the additional metadata are provided as sampling-event data (<<table-06,Table 6>>). Please note that each event dataset consists of two files: the sampling-event dataset and the associated occurrence dataset. The associated occurrence dataset looks like the one in 3.1.2. but needs to be amended with the eventID (mandatory; identifying the event and linking the two datasets) and the occurrenceStatus (recommended to indicate whether a taxon was present or absent at a site). 

Sampling methods are described in the sampling-event dataset with the field samplingProtocol, which provides a name/link to a specific protocol and/or description of the protocol (<<table-06,Table 6>>). The recommended best practice is to have a separate event for each sampling method used. In addition to describing the protocol, the field sampleSizeValue and sampleSizeUnit can be used to indicate the spatial or temporal extent of sampling for the described sampling event, as a measure of sampling effort for each event. In addition, the field samplingEffort can be used to record the total effort spent on the event, for example, when there were multiple nets, multiple microhabitats sampled, or multiple periods of time over which sampling occurred. Additional details about sampling methods are recommended to be included in the freshwater DwC extensions described in section 4.1. 

[[table-06]]
.Terms, definitions, examples, and comments for the terms required by GBIF to publish sampling-event datasets (https://www.gbif.org/data-quality-requirements-sampling-events[more information^] on the specific fields)
[cols="%autowidth"]
|===
|Term	|Freshwater definition |Example |Status |Comment

|term:dwc[eventID]
|identifier for the set of information associated with an Event (something that occurs at a place and time) allowing to link individual occurrences to a specific event; may be a global unique identifier or an identifier specific to the dataset
|"AT:BOKU:DAN_0003:MHS1" [country:institutionCode:sampleCode:method]
|required
|If Occurrence has Event data (i.e., methods metadata describing the sampling event during which the occurrence was recorded), provide the identifier for the information associated with the event. This can e.g. be entered as the occurrenceID without the species code and with the method added.

|===

=== Specific requirements for publishing freshwater data (freshwater amendments)

<<table-07,Table 7>> lists the DwC fields that would be useful to add to freshwater datasets to allow for large-scale data compilation and analysis. Freshwater amendment fields are tagged as:

* freshwater mandatory: as an addition to the GBIF mandatory fields, we recommend mandatory fields for freshwater samples
* freshwater recommended: data that are useful to be reported
* freshwater conditional: data that should be reported, but that are only relevant to particular organism groups or habitats (as indicated)

We provide examples for the content of the fields, and where necessary, even selection lists to choose from.

The freshwater amendments include general fields describing the site where the observation was made, such as the water body name, a description of the location, and the elevation (<<table-07,Table 7>>). In addition, there are fields that describe the sampled habitat, such as the depth of sampling, the microhabitat (e.g., sand, gravel, cobble), and any abiotic measurements taken in the field, including temperature, pH, dissolved oxygen (<<table-07,Table 7>>). Other freshwater-specific habitat descriptions, including the biome, ecosystem functional group, lake zone, and river mesohabitat can be entered in the dynamicProperties field, although the ultimate goal is to create a freshwater DwC extension in GBIF (see section 4.1). 

Further details about the event time and date are also recommended for inclusion (<<table-07,Table 7>>). For example, it is recommended that data providers include year, month, and day as separate columns in their data. This avoids ambiguities that might occur due to regional differences in how year, month, and day are combined into a single field (i.e. confusion of month and day). Furthermore, it is important that all years be entered as four-digit numbers, as historical data (e.g. early 1900s) might be present in GBIF because of digitizing of old records, and full four-digit years ensure that dates are not mishandled. 

Additional fields for observation data include the sex and life stage, both of which are conditional based on the organism group (for example, sex can be determined and is relevant for fish, mammals, birds, and decapods; life stage can be determined and is relevant for copepods, benthic macroinvertebrates, fish, and birds). Furthermore, additional fields provide detail on the identification of the observed taxon, such as references and verification status.

Sampling method details recommended to be included as part of the freshwater DwC extension are fields for sampling equipment (e.g. type of net or sampler), mesh size of nets, and sample processing protocols. Each of these details has been shown to be vital to selecting data for meta-analysis (https://caff.is/freshwater[Lento et al. 2019^]; https://doi.org/10.1111/fwb.13873[Goedkoop et al. 2022^), and including separate fields for them instead of grouping them all within the protocol field increases the chances that complete information will be provided without ambiguities.

[[table-07]]
.Terms, definitions, examples, and comments for the terms recommended to be included with freshwater data. The dataset in which each field should be included (metadata, occurrence or event) is indicated, as is whether fields are mandatory, recommended, or conditional on particular organism groups (https://dwc.tdwg.org/list/[more information^] on the specific fields)
[cols="%autowidth"]
|===
|Term	|Freshwater definition |Example |Status |Comment |Inclusion

|term:dwc[rightsHolder]
|a person or organisation owning or managing the rights over the resource
|"BOKU University" [University of Natural Resources and Life Sciences, BOKU Vienna]
|strongly recommended
|
|metadata

|===
