== Future prospects 

=== Freshwater DwC extension

While we have recommended that occurrence and sampling-event data be amended with other specific DwC fields when publishing freshwater data (see <<§2.2>> and <<table-07,Table 7>>), several of the fields that should be included in the (meta)data as best practices do not currently have appropriate equivalents in DwC. Our recommendation is that a freshwater DwC extension should be created to allow these fields to be entered and grouped with freshwater data (<<table-08,Table 8>>). Prior to the extension being created, the recommendation is to enter all details in the term:dwc[dynamicProperties] field, but as this field is not searchable, the greatest functionality will result from an extension.

The proposed DwC extension includes the classification of the type of observation (opportunistic, targeted, or assemblage sampling) and type of contribution (professional, community-based research, or citizen science data; <table-08,Table 8>>). In addition, the location of the observation is further described by the biome, ecosystem functional group, and freshwater lake zone or river mesohabitat (conditional on the biome). 

To allow data to be selected more efficiently for freshwater meta-analyses, the freshwater DwC extension also includes fields for the organism group and the season of sampling, as well as specifications for the sampling methods.

[glossary]
==== 3.1.1 Recommended terms for a DwC freshwater extension

freshwaterBiome:: _definition_: ecologically similar components of freshwaters with broadly similar features +
_examples_: "lakes", "rivers", "wetlands", "groundwater", "adjacent to freshwater", ”interstitial” +
_status_: Required +
_comment_: Please classify your event accordingly based on where the observation was made. If observation was in a terrestrial habitat adjacent to freshwater, indicate "adjacent to freshwater". +
_inclusion_: Occurrence

freshwaterEcosystemFunctionalGroup:: _definition_: typology within biomes that classifies ecosystems by joining those with similar ecological conditions +
_examples_: "lowland rivers", "large lakes", "ponds" (see typology for full list) +
_status_: Required +
_comment_: Please follow the definitions of the https://global-ecosystems.org/[IUCN Global Ecosystem Typology^] for consistency +
_inclusion_: Occurrence

freshwaterLakeZone:: _definition_: typology within the lake biome that classifies this ecosystem into habitat zones +
_examples_: "littoral", "sub-littoral", "pelagic", "profundal" +
_status_: Share, if available (based on freshwaterBiome) +
_inclusion_: Occurrence

freshwaterRiverMesohabitat:: _definition_: typology within the river biome that classifies this ecosystem into habitat zones +
_examples_:"riffle", "run", "pool" +
_status_: Share, if available (based on freshwaterBiome) +
_inclusion_: Occurrence

[[table-08]]
.Terms, definitions, examples, and comments for the terms recommended for inclusion in a freshwater DwC extension.
[cols="%autowidth"]
|===
|term	|definition |example(s) |status |comment |inclusion

|freshwaterBiome
|ecologically similar components of freshwaters with broadly similar features
|"lakes" +
"rivers" +
"wetlands" +
"groundwater" +
"adjacent to freshwater" +
”interstitial”
|required
|Please classify your event accordingly based on where the observation was made. If observation was in a terrestrial habitat adjacent to freshwater, indicate "adjacent to freshwater".	
|occurrence

|freshwaterEcosystemFunctionalGroup
|typology within biomes that classifies ecosystems by joining those with similar ecological conditions
|"lowland rivers" +
"large lakes" +
"ponds" +
(see typology for full list)
|required
|Please follow the definitions of the https://global-ecosystems.org/[IUCN Global Ecosystem Typology^] for consistency
|occurrence

|freshwaterLakeZone
|typology within the lake biome that classifies this ecosystem into habitat zones
|"littoral" +
"sub-littoral" +
"pelagic" +
"profundal"
|share, if available (based on freshwaterBiome)
| 
|occurrence

|freshwaterRiverMesohabitat
|typology within the river biome that classifies this ecosystem into habitat zones
|"riffle" +
"run" +
"pool"
|share, if available (based on freshwaterBiome)
| 
|occurrence

|freshwaterTypeOfContribution
|category based on the type of data contribution
|"professional data" +
"community-based research data" +
"citizen science data"
|required
| 
|occurrence

|freshwaterTypeoOfObservation
|category of occurrence and sampling-event data based on the type of observation that was made
|"opportunistic observation" +
"targeted sampling" +
"assemblage sampling"
|required
| 
|occurrence

|freshwaterOrganismGroup
|collections of biologically and ecologically similar organisms that are generally grouped together and described as an assemblage
|"fungi" +
"microbes" +
"benthic algae" +
"phytoplankton" +
"macrophytes" +
"zooplankton" +
"benthic invertebrates" +
"decapods" +
"fish" +
"amphibians" +
"reptiles" +
"birds" +
"mammals"
|required
| 
|occurrence

|freshwaterSeason
|indicates the season in which a sample was collected
|"winter" +
"spring" +
"summer" +
"autumn" +
"wet" +
"dry"
|strongly recommended
| 
|occurrence

|freshwaterSamplingEquipment
|name or description of the sampling instrument that was used for collecting the taxa, including mesh sizes where applicable
|"light trap" +
"500 μm mesh kick net" +
"80 μm mesh plankton net" +
"6.25, 8, 10, 12.5, 15.5, 19.5, 24, 29, 35, 43, 55 mm mesh gill net"
|required	
|It is important that both the sampling equipment and the net mesh size (if nets were used) are provided, as mesh size gives an indication of the size of organisms retained.
|occurrence

|freshwaterSampleProcessing
|name or description of the sample processing protocol (i.e., procedures followed after sample collection to sort and identify taxa)	
|"20x microscope magnification" +
"subsampled with Marchant box until 300 organisms identified - abundance estimated based on the number of cells processed" +
"samples filtered on 45 μm pore size filter paper prior to identification" +
"samples mounted on slide and random transects identified under 500x inverted microscope until 300 individuals filaments or colonies counted and identified" +
|share, if available (based on freshwaterOrganismGroup (fungi, microbes, benthic algae, phytoplankton, zooplankton, benthic macroinvertebrates))
|Provide as much detail as possible about procedures followed in the lab to process and idenfity samples, including any sub-sampling procedures, sample treatment/staining, slide mounting, and magnifications used. If relevant, include a reference to the protocol used.
|occurrence

|===

NOTE: `pink fields indicate that you should choose either of these entries`	

=== Freshwater data tagging

Data portals such as GBIF.org offer a great variety of data but still show limitations in terms of freshwater species. This relates mostly to the fact that freshwater species and freshwater datasets are not specifically tagged and therefore hard to find among millions of terrestrial and marine species and occurrence records. If looking for entire freshwater datasets (e.g. recordings of whole assemblages) this often has to be done through searching for specific freshwater species, which is a time-consuming task.

Freshwater datasets that are submitted to GBIF through a GBIF node or uploaded using https://www.gbif.org/ipt[GBIF Integrated Publishing Toolkit^] (IPT) software should therefore be tagged as “freshwater” to make the dataset more visible to the freshwater community. This can be done by allocating the specific dataset to the “Freshwater Network” during the publication process, after registering it with GBIF.

=== Importance of reliable taxonomy 

The use of organism names is ubiquitous in a wide range of research, environmental management and policy domains. Expert-curated taxonomic databases and tools to query these data are therefore essential for ensuring the quality of biological data. Species information systems for monitoring status and trends of biodiversity (e.g. GBIF) and those dealing with policy concerns (e.g. European Water Framework Directive, Natura 2000 species, commercial, invasive alien species and pest species) benefit from such high-quality tools and databases ensuring the interoperability of data. The last global taxonomic assessment of freshwater species dates back to the year 2008 (https://doi.org/10.1007/978-1-4020-8259-7[Balian et al. 2008^]). This http://fada.biodiversity.be/[Freshwater Animal Diversity Assessment^] (FADA) comprises a global, extensive set of taxa lists for freshwater animal groups (125,530 described species and 11,388 genera). However, these lists were never fully integrated into GBIF. As taxonomy is a living scientific discipline where new taxa are being described and existing taxa are being placed in new taxonomic positions, the FADA database is https://www.naturalsciences.be/en/science/research/biodiversity-in-a-changing-world/projects/infrafada[currently being updated^] with the ultimate goal to serve as up-to-date freshwater animal taxonomic backbone for GBIF as well as for other international infrastructures like the https://www.catalogueoflife.org[Catalogue of Life^] or the data portal of the http://www.freshwaterplatform.eu[Freshwater Information Platform^] (FIP), which is currently rebuilt as “FIPbio”.

=== Interaction and linkages between data infrastructures

Species observed in freshwaters are typically good indicators of the health/status of these ecosystems and are therefore frequently analyzed as part of ecological monitoring programs. The biodiversity data generated during such monitoring routines, in combination with data from other ecological studies in freshwaters, can form an invaluable source of information to support sustainable management and conservation of aquatic ecosystems. However, a large amount of data still remains scattered on individual researchers’ computers and institute servers as well as in different data infrastructures depending on the type of data. This has led to a variety of calls for intense freshwater data mobilization activities as well as a better and more connected infrastructure landscape where data publishing follows the FAIR Principles (e.g. https://doi.org/10.1111/conl.12771[Van Rees et al 2021^]; https://doi.org/10.1111/ele.13931[Maasri et al. 2022^]).

While findability – through capable search engines – seems to be less of a pressing issue, accessibility of data, interoperability between data infrastructures and reusability still play a major role. This guideline seeks to streamline data publication in terms of data reuse and accessibility by making them available through GBIF and by including a specific set of fields for freshwater-relevant information. Alternatively, other publishing platforms that guarantee exchange with GBIF like the data portal of the Freshwater Information Platform (FIPbio) or the South African https://freshwaterbiodiversity.org/[Freshwater Biodiversity Information System^], which both focus on freshwater data, can be used. In any case, we advise that priority be given to infrastructures that provide biogeographic information and are well-connected with GBIF, rather than using simple repositories for data publishing.

Once freshwater data can be more easily filtered within GBIF (through respective tagging of freshwater species), it will be possible to more easily assess global freshwater taxa coverage and to actually identify data and/or research gaps in freshwater biodiversity.
