[glossary][#glossary]
== Glossary

[glossary]
[[anchor]]term:: add short tags corresponding to an anchor name in HTML between brackets (no spaces allowed), then list the term, which should be written as you wish it to appear.
[[authorization]]authorization:: refers to the process of determining which individuals can be afforded different access rights for authentication and data access.
[[decimal-degrees]]decimal degrees:: degrees expressed as a single real number (e.g. −22.343456°). Note that latitudes south of the equator are negative, as are longitudes west of the prime meridian to −180 degrees.
[[generalization]]generalization:: refers here to any modifications carried out to source data to conceal sensitive content, typically by reducing the precision of the data (such as reporting at the level of a watershed, grid or county, citing just the nearest named place, or by deleting some parts of the data). In geographic terms it refers to the conversion of a geographic representation to one with less resolution and less information content; traditionally associated with a change in scale. Also referred elsewhere to as: _fuzzying_, _dummying-up_, etc.

[[assemblage]]assemblage:: a collection of biologically- and ecologically-related taxa within a community (i.e., all individuals in an organism group), following the definition of Fauth et al. (1996)

benthic: organisms that live on the bottom (on or in the substrate) of a body of water or wetland
biome: according to the IUCN Global Ecosystem Typology there are three biomes in freshwater: (1) rivers and streams, (2) lakes, and (3) artificial wetlands, with groundwater, brackish water, palustrine wetlands, and coastal systems grouped within transitional realms
DwC: Darwin Core (https://dwc.tdwg.org/): publishing standard
ecosystem functional group: according to the IUCN Global Ecosystem Typology ecosystem functional groups describe ecological conditions within the realms, e.g., permanent, seasonal or episodic/ephemeral; freeze-thaw; upland or lowland; large or small; etc. 
FIP: Freshwater Information Platform (http://www.freshwaterplatform.eu/)
IPT: Integrated Publishing Toolkit (publishing instance on GBIF)
lake zone: lake habitat zones defined based on depth and characteristics related to light penetration,oxygen levels, substrates and temperature; includes littoral, sub-littoral, profundal, and pelagic
microhabitat: fine-scale habitat differences within a water body, such as areas with different substrate composition.
organism group: collections of biologically- and ecologically-similar organisms that are generally grouped together and described as an assemblage, e.g. benthic invertebrates
realm: according to the IUCN Global Ecosystem Typology there are five realms: (1) terrestrial, (2) freshwater, (3) marine, (4) subterranean, and (5) atmospheric components of the biosphere, as well as transitional zones between realms
river mesohabitat: zones in a river differentiated based on types of flow, including riffles (fast-flowing, shallow, rocky areas), runs (deeper, fast-flowing areas), and pools (areas of slow-flowing or standing water)

<<<
