== Introduction

=== Freshwater data publishing

Freshwaters are vital to human well-being, yet they are among the most threatened ecosystems on the planet (https://doi.org/10.1017/S1464793105006950[Dudgeon et al. 2006^]; https://doi.org/10.1111/brv.12480[Reid et al. 2019^]). Despite increasing efforts over the past decades to protect freshwaters and improve their state, our ability to monitor, detect and manage changes to freshwater ecosystems and their biodiversity is limited by the availability of supporting data (https://geobon.org/science-briefs/[GEO BON & FWBON 2022^]). Recent research highlights the need for better data availability to support scientific analyses (https://doi.org/10.1002/aqc.2958[Darwall et al. 2018^]; https://doi.org/10.1093/biosci/biaa002[Tickner et al. 2020^]; https://doi.org/https://doi.org/10.1002/aqc.3634[Harper et al. 2021^]; https://doi.org/10.1111/conl.12771[Van Rees et al. 2021^]). Data that follow the FAIR principles of _Findability_, _Accessibility_, _Interoperability_ and _Reusability_ (https://doi.org/10.1038/sdata.2016.18[Wilkinson et al. 2016^]) in particular can support advancements in establishing freshwater biodiversity baselines and detecting changes in response to stressors. For example, improved data availability has the potential to facilitate large-scale analyses of spatial patterns and temporal trends in freshwater biodiversity, such as the state of Arctic freshwater biodiversity assessment conducted by the Circumpolar Biodiversity Monitoring Program (https://caff.is/freshwater[Lento et al. 2019^]). Furthermore, improved spatial and temporal coverage of freshwater biodiversity data, particularly from biodiversity hotspots and remote or unique habitats, can support the inclusion of freshwater species in global indices, such as WWF’s freshwater Living Planet Index (https://doi.org/10.1038/s44185-023-00017-3[Ledger et al. 2023^]).

Despite the growing calls for open data and increasing requirements that publicly-funded data be made open access (https://doi.org/10.29379/jedem.v9i2.465[Beno et al. 2017^]; https://doi.org/10.1177/2053951719836258[Sholler et al. 2019^]; <<turak,Turak et al. 2023>>, there remain a number of impediments to data mobilization. These include a lack of capacity (time, funding, expertise) to set up data in the required formats for data publishing, concerns over intellectual property rights (e.g. ownership, attribution) of shared data, lack of incentives to publish data, and a reluctance to publish data prior to publication (https://doi.org/10.29379/jedem.v9i2.465[Beno et al. 2017^]; https://doi.org/10.1007/978-3-319-73250-3_20[Schmidt-Kloiber & De Wever 2018^]; <<turak,Turak et al. 2023>>). In their global survey of data mobilization among freshwater practitioners, <<turak,Turak et al. (2023)>> noted that financial support for publishing and long-term data management of data was a major concern for most respondents. While some of the identified barriers to data mobilization reflect institutional obstacles, such as the lack of funding and data publishing incentives, there is an opportunity to improve the ease with which data providers can share their data.

Potential users of open data may encounter other obstacles, such as a lack of interoperability of data from different data portals, a lack of supporting metadata (e.g. information about sites and methods), ambiguities or inaccuracies in the (meta)data, and difficulties in searching for and selecting relevant data (e.g. finding diversity data only for freshwater species) (https://doi.org/10.29379/jedem.v9i2.465[Beno et al. 2017^]). A number of these issues can possibly be controlled by improving the quality of published data and metadata, for example, by ensuring a standard set of metadata is always provided with the data, ensuring data have relevant tags that will allow them to be located by potential users, and following a standard template for data publishing. For freshwater data, these improvements could facilitate greater and more widespread use of open data from portals such as GBIF, potentially feeding into global biodiversity assessments. 

=== Scope of the guide

This guide describes best practices for freshwater data publishing, including a list of the (meta)data fields that are necessary to describe sample locations and sampling methods in sufficient detail to allow meta-analysis across datasets. One of the aims of the guide is to provide the user with sufficient background information to understand why particular fields are necessary for freshwater data, for example, fields describing the type of freshwater ecosystem in which the organism was observed, or indicating the freshwater organism group to which an individual belongs. This information is intended to improve the quality of published freshwater data.

Another goal of this guide is to make the process of formating data for publication more user-friendly by describing what information should be included in each field and providing freshwater-relevant examples. One of the reasons why scientists are often still reluctant to publish data is that it requires a lot of time that is usually not included in research projects (https://doi.org/10.1007/978-3-319-73250-3_20[Schmidt-Kloiber & De Wever 2018^]). Therefore, it is important that technically straightforward procedures are available to support general freshwater data mobilization. This guidance manual will help to support data publishing by providing instruction on best practices for formatting data, with a focus on the GBIF infrastructures.

=== Target audience

The target audience for this guide is researchers in government, academia and NGOs, as well as all freshwater practitioners (e.g. people engaged in designing and carrying out monitoring), as the best practices described herein offer insights for anyone involved in collecting, recording and managing freshwater data. But in particular, the guide is intended to assist those who are or will be formatting freshwater data with the intent of publishing those data. The goal is to give those individuals the tools needed to ensure the data they publish are consistent with global standards and contain sufficient supporting information to ensure their usefulness in meta-analyses of biodiversity.
